# Generated by Django 5.2.4 on 2025-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_full_description_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина (см)'),
        ),
    ]
